services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: graspop
      POSTGRES_USER: graspop
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - "5432"

  backend:
    image: ghcr.io/eddoww/graspop_planner/backend:latest
    ports:
      - "3021:3001"
    environment:
      DATABASE_URL: postgresql://graspop:${DB_PASSWORD}@db/graspop
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: ghcr.io/eddoww/graspop_planner/frontend:latest
    depends_on:
      - backend
    ports:
      - "3020:80"
    environment:
      VITE_API_URL: http://backend:3001
    restart: unless-stopped

volumes:
  postgres_data:
