services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: graspop
      POSTGRES_USER: graspop
      POSTGRES_PASSWORD: graspoppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graspop"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://graspop:graspoppass@db:5432/graspop
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head && 
              python init_db.py &&
              uvicorn main:app --host 0.0.0.0 --port 3001 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
volumes:
  postgres_data:
