services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: graspop
      POSTGRES_USER: graspop
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - "5432"

  backend:
    image: ghcr.io/eddoww/graspop_planner/backend:latest
    environment:
      DATABASE_URL: postgresql://graspop:${DB_PASSWORD}@db/graspop
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - "3001"

  frontend:
    image: ghcr.io/eddoww/graspop_planner/frontend:latest
    depends_on:
      - backend
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
